// Autogenerated file: do not modify

static const refImport_t ri = {
	sizeof(refImport_t),

	Cvar_Get,
	Cvar_GetVars,
	Cvar_Set,
	Cvar_SetValue,
	Cvar_SetInteger,
	Cvar_VariableString,
	Cvar_VariableValue,
	Cvar_VariableInt,
	Cvar_Clamp,
	Com_DPrintf,
	FS_Gamedir,
	FS_CopyFile,
	FS_CopyFiles,
	FS_RemoveFiles,
	Vid_Restart,
	Vid_GetModeInfo,
	ImageExists,
	LoadPCX,
	LoadTGA,
	LoadJPG,
	WriteTGA,
	WriteJPG,
	LoadBspFile,
	CM_BoxTrace,
	CM_TransformedBoxTrace,
	CM_TransformedBoxTrace,
	CM_ClipTraceToModels,
	CM_BrushTrace,
	CM_RefineBrushTrace
#if _WIN32
,
	Vid_CreateWindow,
	Vid_DestroyWindow
#endif

};

