- if (): cvar, maptype (q2, KP, q3, HL, any text (??)), platform (??), game
- entities:
  - rename class
  - delete
  - set maptype (if specific entity appears)
- fields:
  - set type (for map scaling: angle, vector, distance ... (?))
  - rename
  - delete
  - add
