// Autogenerated file: do not modify

refImport_t ri = {
	sizeof(refImport_t),
	API_VERSION,
	Cmd_AddCommand,
	Cmd_RemoveCommand,
	Cmd_Argc,
	Cmd_Argv,
	Cmd_Args,
	Cbuf_ExecuteText,
	Cvar_Get,
	Cvar_GetVars,
	Cvar_Set,
	Cvar_SetValue,
	Cvar_SetInteger,
	Cvar_VariableString,
	Cvar_VariableValue,
	Cvar_VariableInt,
	Cvar_Clamp,
	Cvar_ClampName,
	Z_Malloc,
	Z_Free,
	CreateMemoryChain,
	AllocChainBlock,
	FreeMemoryChain,
	Hunk_Begin,
	Hunk_Alloc,
	Hunk_End,
	Hunk_Free,
	Sys_Milliseconds,
	Sys_Mkdir,
	Com_Printf,
	Com_DPrintf,
	Com_WPrintf,
	Com_Error,
	FS_FileExists,
	FS_ListFiles,
	FS_LoadFile,
	FS_FreeFile,
	FS_Gamedir,
	MatchWildcard,
	Vid_GetModeInfo,
	Vid_MenuInit,
	ImageExists,
	LoadPCX,
	LoadTGA,
	LoadJPG,
	WriteTGA,
	WriteJPG,
	LoadBspFile
#ifdef _WIN32
,
	Vid_CreateWindow,
	Vid_DestroyWindow
#else
,
	Vid_NewWindow
#endif

};

