// Autogenerated file: do not modify

typedef struct {
	int		struc_size;
	cvar_t*	(*_Cvar_Get) (const char *name, const char *value, int flags);
	void	(*_Cvar_GetVars) (const cvarInfo_t *vars, int count);
	cvar_t*	(*_Cvar_Set) (const char *name, const char *value);
	cvar_t*	(*_Cvar_SetValue) (const char *name, float value);
	cvar_t*	(*_Cvar_SetInteger) (const char *name, int value);
	char*	(*_Cvar_VariableString) (const char *name);
	float	(*_Cvar_VariableValue) (const char *name);
	int	(*_Cvar_VariableInt) (const char *name);
	float	(*_Cvar_Clamp) (cvar_t *cvar, float low, float high);
	float	(*_Cvar_ClampName) (const char *name, float low, float high);
	void	(*_Com_Printf) (const char *str, ...);
	void	(*_Com_DPrintf) (const char *str, ...);
	void	(*_Com_WPrintf) (const char *str, ...);
	bool	(*_FS_FileExists) (const char *filename);
	TList<CStringItem>	(*_FS_ListFiles) (const char *name, int *numfiles, int flags);
	void*	(*_FS_LoadFile) (const char *name, unsigned *size);
	void	(*_FS_FreeFile) (void *buf);
	char*	(*_FS_Gamedir) (void);
	void	(*_FS_CreatePath) (const char *path);
	void	(*_FS_CopyFile) (const char *src, const char *dst);
	void	(*_FS_CopyFiles) (const char *srcMask, const char *dstDir);
	void	(*_FS_RemoveFiles) (const char *mask);
	void	(*_Vid_Restart) (void);
	bool	(*_Vid_GetModeInfo) (int *width, int *height, int mode);
	int	(*_ImageExists) (const char *name, int stop_mask);
	void	(*_LoadPCX) (const char *name, byte **pic, byte **palette, int *width, int *height);
	void	(*_LoadTGA) (const char *name, byte **pic, int *width, int *height);
	void	(*_LoadJPG) (const char *name, byte **pic, int *width, int *height);
	bool	(*_WriteTGA) (const char *name, byte *pic, int width, int height);
	bool	(*_WriteJPG) (const char *name, byte *pic, int width, int height, bool highQuality);
	bspfile_t*	(*_LoadBspFile) (const char *filename, bool clientload, unsigned *checksum);
	void	(*_CM_BoxTrace) (trace_t *tr, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, int headnode, int brushmask);
	void	(*_CM_TransformedBoxTrace) (trace_t *tr, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, int headnode, int brushmask, const vec3_t origin, const vec3_t angles);
	void	(*_CM_TransformedBoxTrace2) (trace_t *tr, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, int headnode, int brushmask, const vec3_t origin, const vec3_t *axis);
	int	(*_CM_BrushTrace) (const vec3_t start, const vec3_t end, int *brushes, int maxBrushes);
	int	(*_CM_RefineBrushTrace) (const vec3_t start, const vec3_t end, int *brushes, int numBrushes);
#ifdef _WIN32
	void*	(*_Vid_CreateWindow) (int width, int height, bool fullscreen);
	void	(*_Vid_DestroyWindow) (bool force);
#endif
} refImport_t;

extern refImport_t ri;

