// Autogenerated file: do not modify

typedef struct {
	int		struc_size;
	void	(*_Cmd_AddCommand) (const char *name, void(*func)(void));
	void	(*_Cmd_RemoveCommand) (const char *name);
	int	(*_Cmd_Argc) (void);
	char*	(*_Cmd_Argv) (int i);
	char*	(*_Cmd_Args) (void);
	cvar_t*	(*_Cvar_Get) (const char *name, const char *value, int flags);
	void	(*_Cvar_GetVars) (const cvarInfo_t *vars, int count);
	cvar_t*	(*_Cvar_Set) (const char *name, const char *value);
	cvar_t*	(*_Cvar_SetValue) (const char *name, float value);
	cvar_t*	(*_Cvar_SetInteger) (const char *name, int value);
	char*	(*_Cvar_VariableString) (const char *name);
	float	(*_Cvar_VariableValue) (const char *name);
	int	(*_Cvar_VariableInt) (const char *name);
	float	(*_Cvar_Clamp) (cvar_t *cvar, float low, float high);
	float	(*_Cvar_ClampName) (const char *name, float low, float high);
	void*	(*_Z_Malloc) (int size);
	void	(*_Z_Free) (void *ptr);
	void*	(*_CreateMemoryChain) (void);
	void*	(*_AllocChainBlock) (void *chain, int size);
	void	(*_FreeMemoryChain) (void *chain);
	void*	(*_Hunk_Begin) (int maxsize);
	void*	(*_Hunk_Alloc) (int size);
	int	(*_Hunk_End) (void);
	void	(*_Hunk_Free) (void *buf);
	int	(*_Sys_Milliseconds) (void);
	void	(*_Com_Printf) (const char *str, ...);
	void	(*_Com_DPrintf) (const char *str, ...);
	void	(*_Com_WPrintf) (const char *str, ...);
	void	(*_Com_FatalError) (const char *fmt, ...);
	void	(*_Com_DropError) (const char *fmt, ...);
#ifdef _WIN32
	int	(*_win32ExceptFilter2) (void);
#endif
	void	(*_appUnwindPrefix) (const char *fmt);
	void	__declspec(noreturn)	(*_appUnwindThrow) (const char *fmt, ...);
	bool	(*_FS_FileExists) (char *filename);
	basenamed_t*	(*_FS_ListFiles) (char *name, int *numfiles, int flags);
	int	(*_FS_LoadFile) (char *name, void **buf);
	void	(*_FS_FreeFile) (void *buf);
	char*	(*_FS_Gamedir) (void);
	void	(*_FS_CreatePath) (char *path);
	void	(*_FS_CopyFile) (char *src, char *dst);
	void	(*_FS_CopyFiles) (char *srcMask, char *dstDir);
	void	(*_FS_RemoveFiles) (char *mask);
	bool	(*_MatchWildcard) (const char *name, const char *mask, bool ignoreCase = false);
	bool	(*_Vid_GetModeInfo) (int *width, int *height, int mode);
	int	(*_ImageExists) (char *name, int stop_mask);
	void	(*_LoadPCX) (char *name, byte **pic, byte **palette, int *width, int *height);
	void	(*_LoadTGA) (char *name, byte **pic, int *width, int *height);
	void	(*_LoadJPG) (char *name, byte **pic, int *width, int *height);
	bool	(*_WriteTGA) (char *name, byte *pic, int width, int height);
	bool	(*_WriteJPG) (char *name, byte *pic, int width, int height, bool highQuality);
	bspfile_t*	(*_LoadBspFile) (char *filename, bool clientload, unsigned *checksum);
	void	(*_CM_BoxTrace) (trace_t *tr, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, int headnode, int brushmask);
	void	(*_CM_TransformedBoxTrace) (trace_t *tr, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, int headnode, int brushmask, const vec3_t origin, const vec3_t angles);
	void	(*_CM_TransformedBoxTrace2) (trace_t *tr, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, int headnode, int brushmask, const vec3_t origin, const vec3_t *axis);
	int	(*_CM_BrushTrace) (const vec3_t start, const vec3_t end, int *brushes, int maxBrushes);
	int	(*_CM_RefineBrushTrace) (const vec3_t start, const vec3_t end, int *brushes, int numBrushes);
#ifdef _WIN32
	void*	(*_Vid_CreateWindow) (int width, int height, bool fullscreen);
	void	(*_Vid_DestroyWindow) (bool force);
#else
	void	(*_Vid_NewWindow) (int width, int height);
#endif
} refImport_t;

extern refImport_t ri;

