// Autogenerated file: do not modify

typedef struct {
	int		struc_size;
	unsigned *flags;
	bool	(*Init) (void);
	void	(*Shutdown) (bool complete);
	void	(*BeginRegistration) (const char *map);
	model_t*	(*RegisterModel) (const char *name);
	image_t*	(*RegisterSkin) (const char *name);
	image_t*	(*RegisterPic) (const char *name);
	void	(*SetSky) (const char *name, float rotate, vec3_t axis);
	void	(*EndRegistration) (void);
	void	(*BeginFrame) (float camera_separation);
	void	(*RenderFrame) (refdef_t *fd);
	void	(*EndFrame) (void);
	void	(*DrawGetPicSize) (int *w, int *h, const char *name);
	void	(*DrawPic) (int x, int y, const char *pic, int color);
	void	(*DrawStretchPic) (int x, int y, int w, int h, const char *name);
	void	(*DrawDetailedPic) (int x, int y, int w, int h, const char *name);
	void	(*DrawChar) (int x, int y, int c, int color);
	void	(*DrawTileClear) (int x, int y, int w, int h, const char *name);
	void	(*DrawFill) (int x, int y, int w, int h, int c);
	void	(*DrawFill2) (int x, int y, int w, int h, unsigned rgba);
	void	(*DrawStretchRaw8) (int x, int y, int w, int h, int cols, int rows, byte *data, unsigned *palette);
	void	(*AppActivate) (bool activate);
	void	(*Screenshot) (int flags, const char *name);
	void	(*ReloadImage) (const char *name);
	void	(*DrawTextPos) (int x, int y, const char *text, unsigned rgba);
	void	(*DrawTextLeft) (const char *text, unsigned rgba);
	void	(*DrawTextRight) (const char *text, unsigned rgba);
	void	(*DrawConChar) (int x, int y, int c, int color);
	float	(*GetClientLight) (void);
} refExport_t;

