// Autogenerated file: do not modify

// don't know why, but VC6 (7-untested) will drop var without following line:
extern const refExport_t re;

const refExport_t re = {
	sizeof(refExport_t),

	GetCaps,
	Init,
	Shutdown,
	BeginRegistration,
	RegisterModel,
	RegisterSkin,
	RegisterPic,
	SetSky,
	EndRegistration,
	BeginFrame,
	RenderFrame,
	EndFrame,
	DrawPic,
	DrawStretchPic,
	DrawDetailedPic,
	DrawChar,
	TileClear,
	Fill,
	Fill8,
	DrawStretchRaw8,
	AppActivate,
	Screenshot,
	DrawTextPos,
	DrawTextLeft,
	DrawTextRight,
	DrawConChar,
	GetClientLight
};

