// Autogenerated file: do not modify

// don't know why, but VC6 (VC7/GCC-untested) will drop var without following line:
extern const refExport_t re;

const refExport_t re = {
	sizeof(refExport_t),

	Init,
	Shutdown,
	LoadNewWorld,
	FinishLoadingWorld,
	RegisterModel,
	RegisterSkin,
	RegisterPic,
	RegisterFont,
	SetSky,
	BeginFrame,
	RenderFrame,
	EndFrame,
	DrawPic,
	DrawStretchPic,
	DrawDetailedPic,
	DrawChar,
	DrawChar,
	TileClear,
	Fill,
	Fill8,
	DrawStretchRaw8,
	AppActivate,
	Screenshot,
	DrawTextPos,
	DrawTextLeft,
	DrawTextRight,
	DrawText3D,
	GetClientLight
#if !NO_DEBUG
,
	DrawBrush
#endif

};

