// Autogenerated file: do not modify

inline bool RE_Init (void)
{
	return re.Init ();
}
inline void RE_Shutdown (bool complete = false)
{
	re.Shutdown (complete);
}
inline void RE_BeginRegistration (const char *map)
{
	re.BeginRegistration (map);
}
inline model_t* RE_RegisterModel (const char *name)
{
	return re.RegisterModel (name);
}
inline image_t* RE_RegisterSkin (const char *name)
{
	return re.RegisterSkin (name);
}
inline image_t* RE_RegisterPic (const char *name)
{
	return re.RegisterPic (name);
}
inline void RE_SetSky (const char *name, float rotate, vec3_t axis)
{
	re.SetSky (name, rotate, axis);
}
inline void RE_EndRegistration (void)
{
	re.EndRegistration ();
}
inline void RE_BeginFrame (float camera_separation)
{
	re.BeginFrame (camera_separation);
}
inline void RE_RenderFrame (refdef_t *fd)
{
	re.RenderFrame (fd);
}
inline void RE_EndFrame (void)
{
	re.EndFrame ();
}
inline void RE_DrawGetPicSize (int *w, int *h, const char *name)
{
	re.DrawGetPicSize (w, h, name);
}
inline void RE_DrawPic (int x, int y, const char *pic, int color = C_WHITE)
{
	re.DrawPic (x, y, pic, color);
}
inline void RE_DrawStretchPic (int x, int y, int w, int h, const char *name)
{
	re.DrawStretchPic (x, y, w, h, name);
}
inline void RE_DrawDetailedPic (int x, int y, int w, int h, const char *name)
{
	re.DrawDetailedPic (x, y, w, h, name);
}
inline void RE_DrawChar (int x, int y, int c, int color = C_WHITE)
{
	re.DrawChar (x, y, c, color);
}
inline void RE_DrawTileClear (int x, int y, int w, int h, const char *name)
{
	re.DrawTileClear (x, y, w, h, name);
}
inline void RE_DrawFill (int x, int y, int w, int h, int c)
{
	re.DrawFill (x, y, w, h, c);
}
inline void RE_DrawFill2 (int x, int y, int w, int h, unsigned rgba)
{
	re.DrawFill2 (x, y, w, h, rgba);
}
inline void RE_DrawStretchRaw8 (int x, int y, int w, int h, int cols, int rows, byte *data, unsigned *palette)
{
	re.DrawStretchRaw8 (x, y, w, h, cols, rows, data, palette);
}
inline void RE_AppActivate (bool activate)
{
	re.AppActivate (activate);
}
inline void RE_Screenshot (int flags, const char *name)
{
	re.Screenshot (flags, name);
}
inline void RE_ReloadImage (const char *name)
{
	re.ReloadImage (name);
}
inline void RE_DrawTextPos (int x, int y, const char *text, unsigned rgba)
{
	re.DrawTextPos (x, y, text, rgba);
}
inline void RE_DrawTextLeft (const char *text, unsigned rgba)
{
	re.DrawTextLeft (text, rgba);
}
inline void RE_DrawTextRight (const char *text, unsigned rgba)
{
	re.DrawTextRight (text, rgba);
}
inline void RE_DrawConChar (int x, int y, int c, int color = C_WHITE)
{
	re.DrawConChar (x, y, c, color);
}
inline float RE_GetClientLight (void)
{
	return re.GetClientLight ();
}
